### ISSUE TITLE
Structures generate only if the main world has structures

### ISSUE THREAD

**Issue by samuelvitry** [Multiverse/Multiverse-Core#2310]
I got a problem with the lastest version of multiverse on spigot 1.16.1 and paper 1.16.1 : the structure won't generate even when I create a world specifying -a true at the end that still wouldn't work, I've tried recreating the world, that still doesn't work.
I'm running spigot and now paper on 1.16.1 on a server hosted by omg serv, i'm creating vanilla normal world. Also spawner generate but not stronghold/mineshaft/village/shipwreck/etc...
Thank you for reading me and sorry for bad english.

**Comment by crizyx** [comment]
Same problem

**Comment by Shuba-Shuba** [comment]
I'm also having that issue on spigot 1.16.1

**Comment by sdocy503** [comment]
I'm having the opposite problem, I'm trying to make a superflat world with no villages and when I specify -a false the villages still generate and testing if the issue above affected my I also tried running the command without -a false and the villages still generated.  I tested this on 1.16.1 spigot and paper.

**Comment by nicegamer7** [comment]
Looking into how the `/mv create` command works, it would appear this is a Spigot issue. I'll let them know.

**Comment by nicegamer7** [comment]
It seems the server is using the `generate-structures` from `server.properties` instead of listening to MV. Can someone confirm this for me.

So, if no structures are generated for you, I expect the setting to be `false`, and if structures are always generated, I expect it to be `true`.

**Comment by sdocy503** [comment]
I checked my settings and I do have generate structures set to true.

**Comment by nicegamer7** [comment]
As was just discussed on Discord:

It appears the server uses the setting of the main world. So once the setting is changed in `server.properties`, you can delete the main world and then every world will be generated using the new setting.

**Comment by sdocy503** [comment]
I need structures on some of my other worlds though so I think I'll wait till spigot fixes the issue, as I only have one world that doesn't need structures while the rest do need structures.

**Comment by nicegamer7** [comment]
I've just reported the issue [here](https://hub.spigotmc.org/jira/browse/SPIGOT-5901), so keep an eye on it!

**Comment by nicegamer7** [comment]
It's just been marked as fixed! I'll keep this issue open until someone confirms it's working. Reminder: Update using BuildTools if you're using Spigot, and if you're using Paper you'll need to wait for them to update their upstream sources.

**Comment by sdocy503** [comment]
Not working on latest paper yet, will keep an eye out for a new version of that to see when it gets fixed.  I'll reply here when that happens.

**Comment by sdocy503** [comment]
Just tested on a spigot server, made a super flat world with structures off and no villages were found, while the main world that had structures on did have structures, so seems fixed on spigot atleast.

**Comment by nicegamer7** [comment]
Should be working on Paper #27, could someone confirm?

**Comment by meibeeart** [comment]
I am having the same issue. Just to confirm I just need to run build tools to fix this?

**Comment by nicegamer7** [comment]
Yes, that's correct. I'm unsure on whether you'll need to regenerate your worlds though.

**Comment by samuelvitry** [comment]
Ok sorry for not updating earlier but I fix the issue, as you said it multiverses use the settings in server.propertie and in my case the default world was a void. So I switch my classic and void which fix the issue. Also I have reported a bug in multi nether portal which doesn’t exist anymore because player can only take portal in the default world.

**Comment by Uight** [comment]
I just tested it on my Testserver with Paper Spigot 27.
The only difference now is that i can actually use the locate command and it will find structures. However they still wont generate. Not sure to what this is related tho

**Comment by meibeeart** [comment]
I used the most recent Build Tool and regenerated my nether, but there is still no buildings generating.

**Comment by Riiwarin** [comment]
Same Problem for me. I made a custom world with WorldPainter in the 1.14 times without generatining structeres. With the switch to spigot 1.16.1 new worlds wont generate anymore structures. (another overworld, nether & end) After updating with build tools the /locate command works, but it shows me just where would be structures, when there where there.
Every of my possible configs have active structure generation.
It seems for me spigot or multiverse didn't reads a config, instead information in the standard world map.

**Comment by meibeeart** [comment]
I just checked with NBTExplorer and my Generate_Features was already set to 1

**Comment by nicegamer7** [comment]
Sorry for the radio silence everyone, I've been a bit busy lately. I will see if I can get this sorted this weekend.

**Comment by josephrooks** [comment]
Hoping to clarify exactly what this is affecting for myself, if you all can help - Are a normal world, world_nether, and world_the_end created outside of Multiverse going to be affected by this at all? Or is it only going to affect worlds created through /mv commands or by importing through mv?

**Comment by NobleStrike** [comment]
I have figured out the source of the issue and determined some predictability to it. This should lead us to who and where should be patching it.
https://github.com/Multiverse/Multiverse-Core/issues/2339

**Comment by nicegamer7** [comment]
I'm going to have my Spigot ticket reopened.

https://hub.spigotmc.org/jira/browse/SPIGOT-5901

**Comment by nicegamer7** [comment]
It has been marked as fixed again.

Someone please confirm.

**Comment by nicegamer7** [comment]
I've just confirmed it to be working on my end. I'll close this once the fix lands in Paper and another user confirms it's working for them!

**Comment by nicegamer7** [comment]
This problem should be fixed in Paper Build 93, but I'm not home to test it myself.

**Comment by TheRealAws** [comment]
@nicegamer7 
Using Paper Build 98. 
Nether structures seem to now generate correctly.
End structures still seem to fail to generate and /locate command option now no longer works with the output of "Could not find that structure nearby".

**Comment by NobleStrike** [comment]
> @nicegamer7
> Using Paper Build 98.
> Nether structures seem to now generate correctly.
> End structures still seem to fail to generate and /locate command option now no longer works with the output of "Could not find that structure nearby".

Is this a fresh world? Once a chuck is generated it wont retry to make a structure in the same spot. Essentially causing minor map damage if your running a map with a playerbase during this issue. I've also found the maps think they see it in /locate but nothing is generated. However setting the main mans level.dat in two places to allow structures fixes it in newly generated chunks, not old ones.

I'll do a deep test tomorrow to see if this is patched or if any behavior of the issue has been altered. However someone who can code and understands this topic could probably figure it out by just looking at the code changes...

**Comment by TheRealAws** [comment]
> > @nicegamer7
> > Using Paper Build 98.
> > Nether structures seem to now generate correctly.
> > End structures still seem to fail to generate and /locate command option now no longer works with the output of "Could not find that structure nearby".
> 
> Is this a fresh world? Once a chuck is generated it wont retry to make a structure in the same spot. Essentially causing minor map damage if your running a map with a playerbase during this issue. I've also found the maps think they see it in /locate but nothing is generated. However setting the main mans level.dat in two places to allow structures fixes it in newly generated chunks, not old ones.
> 
> I'll do a deep test tomorrow to see if this is patched or if any behavior of the issue has been altered. However someone who can code and understands this topic could probably figure it out by just looking at the code changes...

Yes, this was from both fresh install worlds of both Nether and End. Yes, it is a map with a playerbase going, however myself being the first and currently still the only user to have entered.

**Comment by TheRealAws** [comment]
As of Paper Build 99, End locate command and Structures seem to now be spawning correctly.

**Comment by Comitant** [comment]
> 
> 
> As of Paper Build 99, End locate command and Structures seem to now be spawning correctly.

Did spigot fix this as well?

**Comment by nicegamer7** [comment]
Yes, I believe it's been fixed. If anyone still has this issue on newly generated worlds (and has instructions on how to reproduce), feel free to reopen this issue.
